## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python

os:
  - linux

dist: xenial
  
python:
  - 3.6

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install --user flake8
  - pip install --user pytest
  - pip install --user pytest-mock
  - pip install .

script:
  - flake8
  - pytest
