## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python

os:
  - linux

dist: xenial
  
python:
  - 3.6

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install flake8
  - pip install pytest
  - pip install pytest-mock
  - pip install .

script:
  - flake8
  - pytest -vv
